Module StringTransModule

    Function encryptString(n_letter As String) As String
        Dim t_char As String = ""
        Select Case n_letter
            'Case for Highcase
            Case "A"
                t_char = "q"
            Case "B"
                t_char = "o"
            Case "C"
                t_char = "x"
            Case "D"
                t_char = "z"
            Case "E"
                t_char = "a"
            Case "F"
                t_char = "d"
            Case "G"
                t_char = "t"
            Case "H"
                t_char = "i"
            Case "I"
                t_char = "k"
            Case "J"
                t_char = "b"
            Case "K"
                t_char = "u"
            Case "L"
                t_char = "m"
            Case "M"
                t_char = "n"
            Case "N"
                t_char = "f"
            Case "O"
                t_char = "e"
            Case "P"
                t_char = "g"
            Case "Q"
                t_char = "r"
            Case "R"
                t_char = "l"
            Case "S"
                t_char = "y"
            Case "T"
                t_char = "j"
            Case "U"
                t_char = "h"
            Case "V"
                t_char = "s"
            Case "W"
                t_char = "p"
            Case "X"
                t_char = "y"
            Case "Y"
                t_char = "v"
            Case "Z"
                t_char = "w"

            'Case for lowcase
            Case "a"
                t_char = "Q"
            Case "b"
                t_char = "O"
            Case "c"
                t_char = "X"
            Case "d"
                t_char = "Z"
            Case "e"
                t_char = "A"
            Case "f"
                t_char = "D"
            Case "g"
                t_char = "T"
            Case "h"
                t_char = "I"
            Case "i"
                t_char = "K"
            Case "j"
                t_char = "B"
            Case "k"
                t_char = "U"
            Case "l"
                t_char = "M"
            Case "m"
                t_char = "N"
            Case "n"
                t_char = "F"
            Case "o"
                t_char = "E"
            Case "p"
                t_char = "G"
            Case "q"
                t_char = "R"
            Case "r"
                t_char = "L"
            Case "s"
                t_char = "Y"
            Case "t"
                t_char = "J"
            Case "u"
                t_char = "H"
            Case "v"
                t_char = "S"
            Case "w"
                t_char = "P"
            Case "x"
                t_char = "Y"
            Case "y"
                t_char = "V"
            Case "z"
                t_char = "W"

            'Case for numbers
            Case "1"
                t_char = "6"
            Case "2"
                t_char = "2"
            Case "3"
                t_char = "9"
            Case "4"
                t_char = "0"
            Case "5"
                t_char = "8"
            Case "6"
                t_char = "1"
            Case "7"
                t_char = "8"
            Case "8"
                t_char = "5"
            Case "9"
                t_char = "7"
            Case "0"
                t_char = "3"


            'Case for Special Char
            Case "["
                t_char = "~"
            Case "~"
                t_char = "`"
            Case "`"
                t_char = "!"
            Case "!"
                t_char = "@"
            Case "@"
                t_char = "#"
            Case "#"
                t_char = "$"
            Case "$"
                t_char = "%"
            Case "%"
                t_char = "^"
            Case "^"
                t_char = "&"
            Case "&"
                t_char = "*"
            Case "("
                t_char = ")"
            Case ")"
                t_char = "-"
            Case "-"
                t_char = "+"
            Case "+"
                t_char = "="
            Case "="
                t_char = "|"
            Case "|"
                t_char = "{"
            Case "{"
                t_char = "}"
            Case "'"
                t_char = ":"
            Case ":"
                t_char = ";"
            Case ";"
                t_char = "."
            Case "."
                t_char = ","
            Case ","
                t_char = "<"
            Case "<"
                t_char = ">"
            Case ">"
                t_char = "/"
            Case "/"
                t_char = "?"
            Case "?"
                t_char = "]"
            Case "]"
                t_char = "\"
            Case "\"
                t_char = "["

        End Select
        Return t_char
    End Function

    Function decryptString(n_letter As String) As String
        Dim t_char As String = ""
        Select Case n_letter
            'Case for Highcase
            Case "q"
                t_char = "A"
            Case "o"
                t_char = "B"
            Case "x"
                t_char = "C"
            Case "z"
                t_char = "D"
            Case "a"
                t_char = "E"
            Case "d"
                t_char = "F"
            Case "t"
                t_char = "G"
            Case "i"
                t_char = "H"
            Case "k"
                t_char = "I"
            Case "b"
                t_char = "J"
            Case "u"
                t_char = "K"
            Case "m"
                t_char = "L"
            Case "n"
                t_char = "M"
            Case "f"
                t_char = "N"
            Case "e"
                t_char = "O"
            Case "g"
                t_char = "P"
            Case "r"
                t_char = "Q"
            Case "l"
                t_char = "R"
            Case "y"
                t_char = "S"
            Case "j"
                t_char = "T"
            Case "h"
                t_char = "U"
            Case "s"
                t_char = "V"
            Case "p"
                t_char = "W"
            Case "y"
                t_char = "X"
            Case "v"
                t_char = "Y"
            Case "w"
                t_char = "Z"

            'Case for lowcase
            Case "Q"
                t_char = "a"
            Case "O"
                t_char = "b"
            Case "X"
                t_char = "c"
            Case "Z"
                t_char = "d"
            Case "A"
                t_char = "e"
            Case "D"
                t_char = "f"
            Case "T"
                t_char = "g"
            Case "I"
                t_char = "h"
            Case "K"
                t_char = "i"
            Case "B"
                t_char = "j"
            Case "U"
                t_char = "k"
            Case "M"
                t_char = "l"
            Case "N"
                t_char = "m"
            Case "F"
                t_char = "n"
            Case "E"
                t_char = "o"
            Case "G"
                t_char = "p"
            Case "R"
                t_char = "q"
            Case "L"
                t_char = "r"
            Case "Y"
                t_char = "s"
            Case "J"
                t_char = "t"
            Case "H"
                t_char = "u"
            Case "S"
                t_char = "v"
            Case "P"
                t_char = "w"
            Case "Y"
                t_char = "x"
            Case "V"
                t_char = "y"
            Case "W"
                t_char = "z"

            'Case for numbers
            Case "6"
                t_char = "1"
            Case "4"
                t_char = "2"
            Case "9"
                t_char = "3"
            Case "0"
                t_char = "4"
            Case "2"
                t_char = "5"
            Case "1"
                t_char = "6"
            Case "8"
                t_char = "7"
            Case "5"
                t_char = "8"
            Case "7"
                t_char = "9"
            Case "3"
                t_char = "0"

            'Case for white space
            Case "%"
                t_char = " "

            'Case for Special Char
            Case "~"
                t_char = "["
            Case "`"
                t_char = "~"
            Case "!"
                t_char = "`"
            Case "@"
                t_char = "!"
            Case "#"
                t_char = "@"
            Case "$"
                t_char = "#"
            Case "%"
                t_char = "$"
            Case "^"
                t_char = "%"
            Case "&"
                t_char = "^"
            Case "*"
                t_char = "&"
            Case ")"
                t_char = "("
            Case "-"
                t_char = ")"
            Case "+"
                t_char = "-"
            Case "="
                t_char = "+"
            Case "|"
                t_char = "="
            Case "{"
                t_char = "|"
            Case "}"
                t_char = "{"
            Case ":"
                t_char = "'"
            Case ";"
                t_char = ":"
            Case "."
                t_char = ";"
            Case ","
                t_char = "."
            Case "<"
                t_char = ","
            Case ">"
                t_char = "<"
            Case "/"
                t_char = ">"
            Case "?"
                t_char = "/"
            Case "]"
                t_char = "?"
            Case "\"
                t_char = "]"
            Case "["
                t_char = "\"

        End Select
        Return t_char
    End Function
    Function encrypt(str As String) As String
        Dim x As Integer
        Dim out As String = ""
        For x = 1 To Len(str)
            out &= encryptString(Mid(str, x, 1))
        Next x
        Return out
    End Function

    Function decrypt(str As String) As String
        Dim x As Integer
        Dim out As String = ""
        out = ""
        For x = 1 To Len(str)
            out &= decryptString(Mid(str, x, 1))
        Next x
        Return out
    End Function

End Module
